class WorkoutsList {
// Class responsible for showing workouts (To-do : turn it into API)
  static List allWorkoutsList = [
    {
      "workOutTitle": "Mountain climb",
      "imagePath": "imgs/mountain_climb.png",
      "timeLeftInHour": "1",
      "movesNumber": "08",
      "setsNumber": "22",
      "durationInMinutes": "15",
      "rating": "2",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "3,00",
      "hasFreeTrial": "true",
      "dailyFreeWorkout": "true",
      "url":
          "https://media.istockphoto.com/id/1231938416/video/young-man-exercising-at-home-slow-motion-of-man-holding-hands-on-floor-and-doing-mountain.mp4?s=mp4-640x640-is&k=20&c=Ys8jI-1B5r1arn50I2WHaOokVbr2irqrVcNk_kS1ms0="
    },
    {
      "workOutTitle": "Sit up",
      "imagePath": "imgs/situp.png",
      "timeLeftInHour": "40",
      "movesNumber": "10",
      "setsNumber": "10",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
      "isDiscounted": "true",
      "url":
          "https://media.istockphoto.com/id/1409527370/video/determined-man-doing-sit-ups.mp4?s=mp4-640x640-is&k=20&c=gzINAiqGjQ6JAsgl7DpJp3wcTaUu5PLG7IoQutDopfQ="
    },
    {
      "workOutTitle": "Lunges",
      "imagePath": "imgs/lunges.png",
      "timeLeftInHour": "12",
      "movesNumber": "25",
      "setsNumber": "10",
      "durationInMinutes": "44",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "12,00",
      "hasFreeTrial": "false",
      "url":
          "https://media.istockphoto.com/id/1352910571/video/muscular-athletic-young-man-training-for-body-building-at-home.mp4?s=mp4-640x640-is&k=20&c=UR6Q3iEw3nQARmBivEKTjqqgfBtu5O5ZL1aWZxz6yNA="
    },
  ];

  static List hardWorkoutsList = [
    {
      "workOutTitle": "Millitary Press",
      "imagePath": "imgs/militiary_press.png",
      "timeLeftInHour": "11",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "15,00",
      "hasFreeTrial": "false",
      "isWorkoutOfDay": "true",
      "isDiscounted": "true",
      "url":
          "https://media.istockphoto.com/id/1387721018/video/male-bodybuilder-doing-overhead-shoulder-push-press.mp4?s=mp4-640x640-is&k=20&c=IZi5jQQ6eNgEa78yRg2wMRQgDUrZrMfexLYcmgw4Eng="
    },
    {
      "workOutTitle": "Head Crusher",
      "imagePath": "imgs/head_crusher.png",
      "timeLeftInHour": "9",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "1",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
      "url":
          "https://media.istockphoto.com/id/1267927496/video/confident-fit-guy-with-naked-torso-making-exercises-for-hands-with-dumbbell.mp4?s=mp4-640x640-is&k=20&c=zlDiDfBrs-R7Ha4VdewDe0hZhzcQ2nOn6G4dlhAQuWg="
    },
    {
      "workOutTitle": "Millitary Dumbbell Press",
      "imagePath": "imgs/militiary_dumbell.png",
      "timeLeftInHour": "11",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "2",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
      "url":
          "https://media.istockphoto.com/id/1024253488/video/muscular-man-in-the-gym-training-with-dumbbells-guy-pumps-his-deltoid-muscle.mp4?s=mp4-640x640-is&k=20&c=F8lq673IXR0KGyiqXvVeppMP-Ffqdj0Z8bOxpBY-4rY="
    },
    {
      "workOutTitle": "Head Crusher",
      "imagePath": "imgs/head_crusher.png",
      "timeLeftInHour": "11",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "15,00",
      "hasFreeTrial": "false",
      "isWorkoutOfDay": "true",
      "isDiscounted": "true",
      "url":
          "https://media.istockphoto.com/id/1267927496/video/confident-fit-guy-with-naked-torso-making-exercises-for-hands-with-dumbbell.mp4?s=mp4-640x640-is&k=20&c=zlDiDfBrs-R7Ha4VdewDe0hZhzcQ2nOn6G4dlhAQuWg="
    },
    {
      "workOutTitle": "hard muscular exercises",
      "imagePath": "imgs/GetStartedOverlay.png",
      "timeLeftInHour": "9",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "1",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
    },
    {
      "workOutTitle": "Millitary Dumbbell Press",
      "imagePath": "imgs/militiary_dumbell.png",
      "timeLeftInHour": "11",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "2",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
      "dailyFreeWorkout": "true",
      "url":
          "https://media.istockphoto.com/id/1024253488/video/muscular-man-in-the-gym-training-with-dumbbells-guy-pumps-his-deltoid-muscle.mp4?s=mp4-640x640-is&k=20&c=F8lq673IXR0KGyiqXvVeppMP-Ffqdj0Z8bOxpBY-4rY="
    },
  ];

  static List popularWorkoutsList = [
    {
      "workOutTitle": "Pullup",
      "imagePath": "imgs/pullup.png",
      "timeLeftInHour": "10",
      "movesNumber": "40",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "5",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
      "url":
          "https://media.istockphoto.com/id/1442093372/video/pull-up-fitness-and-strong-man-training-in-the-gym-for-body-goal-motivation-and-workout.mp4?s=mp4-640x640-is&k=20&c=qj1VmxXWiAgSbB1rvdAdwQVxvHxrvFhZ9OmzOFElets="
    },
    {
      "workOutTitle": "Concentration Curl",
      "imagePath": "imgs/concentration_curl.png",
      "timeLeftInHour": "22",
      "movesNumber": "40",
      "setsNumber": "20",
      "durationInMinutes": "30",
      "rating": "5",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "30,00",
      "hasFreeTrial": "true",
      "isDiscounted": "true",
      "dailyFreeWorkout": "true",
      "url":
          "https://media.istockphoto.com/id/1352956329/video/muscular-athletic-young-man-training-for-body-building-at-home.mp4?s=mp4-640x640-is&k=20&c=nHK-qCW4nUMnNutvQR_4rZuFs3wNN9dJqXnwFiSfB_E="
    },
    {
      "workOutTitle": "Shoulder",
      "imagePath": "imgs/shoulder.png",
      "timeLeftInHour": "23",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "3",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
      "url":
          "https://media.istockphoto.com/id/1300513351/video/athletic-man-is-training-in-living-room-lifting-dumbbells-tensing-muscles-of-arms-working.mp4?s=mp4-640x640-is&k=20&c=4C3dJDFw4eSy4CIC8xBlDLX3u22UVkBRqG9jhmx0dD4="
    },
    {
      "workOutTitle": "Flat Bench Dumbell",
      "imagePath": "imgs/last.png",
      "timeLeftInHour": "10",
      "movesNumber": "40",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "5",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
      "url":
          "https://media.istockphoto.com/id/1353005146/video/muscular-athletic-young-man-training-for-body-building-at-home.mp4?s=mp4-640x640-is&k=20&c=MRrHQCDLCJRLLywvJpCu8AvfI68T3Mn5IrY_BlOJ-X8="
    },
    {
      "workOutTitle": "hard muscular exercises",
      "imagePath": "imgs/GetStartedOverlay.png",
      "timeLeftInHour": "22",
      "movesNumber": "40",
      "setsNumber": "20",
      "durationInMinutes": "30",
      "rating": "5",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "30,00",
      "hasFreeTrial": "true",
      "dailyFreeWorkout": "true",
    },
    {
      "workOutTitle": "random hard exercises",
      "imagePath": "imgs/welcomePageOverlay.png",
      "timeLeftInHour": "23",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "3",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
  ];

  static List fullBodyWorkoutsList = [
    {
      "workOutTitle": "Hard exercises",
      "imagePath": "imgs/loginOverlayImg.png",
      "timeLeftInHour": "19",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
    {
      "workOutTitle": "hard muscular exercises",
      "imagePath": "imgs/GetStartedOverlay.png",
      "timeLeftInHour": "18",
      "movesNumber": "24",
      "setsNumber": "12",
      "durationInMinutes": "20",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "8,00",
      "hasFreeTrial": "true",
    },
    {
      "workOutTitle": "random hard exercises",
      "imagePath": "imgs/welcomePageOverlay.png",
      "timeLeftInHour": "23",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "3",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "Hard exercises",
      "imagePath": "imgs/loginOverlayImg.png",
      "timeLeftInHour": "19",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "hard muscular exercises",
      "imagePath": "imgs/GetStartedOverlay.png",
      "timeLeftInHour": "18",
      "movesNumber": "24",
      "setsNumber": "12",
      "durationInMinutes": "20",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "8,00",
      "hasFreeTrial": "true",
      "dailyFreeWorkout": "true",
    },
    {
      "workOutTitle": "random hard exercises",
      "imagePath": "imgs/welcomePageOverlay.png",
      "timeLeftInHour": "23",
      "movesNumber": "16",
      "setsNumber": "12",
      "durationInMinutes": "30",
      "rating": "3",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "5,00",
      "hasFreeTrial": "true",
    },
  ];

  static List crossFit = [
    {
      "workOutTitle": "Hard exercises",
      "imagePath": "imgs/loginOverlayImg.png",
      "timeLeftInHour": "18",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "hard muscular exercises",
      "imagePath": "imgs/GetStartedOverlay.png",
      "timeLeftInHour": "16",
      "movesNumber": "100",
      "setsNumber": "30",
      "durationInMinutes": "55",
      "rating": "5",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "55,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
    {
      "workOutTitle": "random hard exercises",
      "imagePath": "imgs/welcomePageOverlay.png",
      "timeLeftInHour": "7",
      "movesNumber": "50",
      "setsNumber": "0",
      "durationInMinutes": "32",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "24,00",
      "hasFreeTrial": "true",
    },
    {
      "workOutTitle": "Hard exercises",
      "imagePath": "imgs/loginOverlayImg.png",
      "timeLeftInHour": "18",
      "movesNumber": "25",
      "setsNumber": "3",
      "durationInMinutes": "12",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "25,00",
      "hasFreeTrial": "true",
      "isDiscounted": "true",
    },
    {
      "workOutTitle": "hard muscular exercises",
      "imagePath": "imgs/GetStartedOverlay.png",
      "timeLeftInHour": "16",
      "movesNumber": "100",
      "setsNumber": "30",
      "durationInMinutes": "55",
      "rating": "5",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "55,00",
      "hasFreeTrial": "true",
      "isWorkoutOfDay": "true",
    },
    {
      "workOutTitle": "random hard exercises",
      "imagePath": "imgs/welcomePageOverlay.png",
      "timeLeftInHour": "7",
      "movesNumber": "50",
      "setsNumber": "0",
      "durationInMinutes": "32",
      "rating": "4",
      "description": "Description here",
      "reviews": "reviews",
      "comments": "comments",
      "priceInDollars": "24,00",
      "hasFreeTrial": "true",
      "dailyFreeWorkout": "true",
    },
  ];
}
